name: Build

on:
  push:
    branches:
      - master
    paths:
      - "!.idea"
      - "build-logic"
      - "Panda"
      - "patches/api/*.patch"
      - "patches/server/*.patch"
      - "patches/SpecialSource/*.patch"
      - "patches/SpecialSource2/*.patch"
      - "SpecialSource"
      - "SpecialSource2"
      - "!.gitattributes"
      - "!.gitignore"
      - ".gitmodules"
      - "colosseum.sh"
      - "!LICENSE"
      - "!README.md"
      - "settings.gradle.kts"
  pull_request:
    branches:
      - master
    paths:
      - "!.idea"
      - "build-logic"
      - "Panda"
      - "patches/api/*.patch"
      - "patches/server/*.patch"
      - "patches/SpecialSource/*.patch"
      - "patches/SpecialSource2/*.patch"
      - "SpecialSource"
      - "SpecialSource2"
      - "!.gitattributes"
      - "!.gitignore"
      - ".gitmodules"
      - "colosseum.sh"
      - "!LICENSE"
      - "!README.md"
      - "settings.gradle.kts"
  workflow_dispatch:


permissions:
  contents: read


defaults:
  run:
    shell: bash


jobs:
  build:
    name: Build jar on Java ${{ matrix.java-version }}
    strategy:
      fail-fast: false
      matrix:
        # JDK 25 is temporarily dropped, because of Gradle.
        java-version: [8, 11, 17, 21]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v5
        with:
          path: ./tmp
          key: ${{ runner.os }}-tmp-${{ github.repository }}-${{ hashFiles('**/*.patch') }}
          restore-keys: |
            ${{ runner.os }}-tmp-

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: ${{ matrix.java-version }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      # https://github.com/orgs/community/discussions/160496
      - name: Build Spigot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global advice.detachedHead false
          ./colosseum.sh b

      - name: Publish package
        if: ${{ github.ref_name == 'master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && matrix.java-version == '8' }}
        run: ./gradlew publish
        env:
          COLOSSEUM_MAVEN_URL: ${{ secrets.COLOSSEUM_MAVEN }}
          COLOSSEUM_MAVEN_USERNAME: ${{ secrets.COLOSSEUM_MAVEN_USERNAME }}
          COLOSSEUM_MAVEN_PASSWORD: ${{ secrets.COLOSSEUM_MAVEN_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ColosseumSpigot-API-${{ github.run_id }}-java-${{ matrix.java-version }}
          path: ./ColosseumSpigot-API/build/libs/*.jar
          retention-days: 1
          overwrite: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        with:
          name: ColosseumSpigot-${{ github.run_id }}-java-${{ matrix.java-version }}
          path: ./ColosseumSpigot-Server/build/libs/*.jar
          retention-days: 1
          overwrite: true